### ISSUE TITLE
Unused arguments in wm.EditEntities.hideMenu

### ISSUE THREAD

**Issue by Joncom** [phoboslab/Impact#15]
https://github.com/phoboslab/Impact/blob/f461c2f4054dac37dea351d8fe3440eae6a2f47e/lib/weltmeister/edit-entities.js#L529

**Comment by gamecubate** [comment]
PR #22

**Comment by gamecubate** [comment]
Can you do the merge and close this issue?

**Comment by Joncom** [comment]
A lot of unrelated white space changes in there..

**Comment by gamecubate** [comment]
Not from me. I used vim on the one file and made the one change.

**Comment by gamecubate** [comment]
Double-checked and the problem is actually from my side, i.e., the develop branch, created months ago, and inadvertently space-modified by me. Will delete said branch and re-push to master, which will make for cleaner changes. Also, there isn't a need for a develop branch at this stage, given that the issues you raised easily qualify as master hotfixes. Thanks for checking. Will re-push shortly.

**Comment by gamecubate** [comment]
New PR. #26
